"""changed field ProjectInvitation: user to invited

Revision ID: 10958f58ad77
Revises: 4e976a8ca55a
Create Date: 2025-09-22 03:39:25.553224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10958f58ad77'
down_revision: Union[str, Sequence[str], None] = '4e976a8ca55a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('otps')
    op.add_column('projectinvitations', sa.Column('invited_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('projectinvitations_user_id_fkey'), 'projectinvitations', type_='foreignkey')
    op.create_foreign_key(None, 'projectinvitations', 'users', ['invited_id'], ['id'])
    op.drop_column('projectinvitations', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projectinvitations', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projectinvitations', type_='foreignkey')
    op.create_foreign_key(op.f('projectinvitations_user_id_fkey'), 'projectinvitations', 'users', ['user_id'], ['id'])
    op.drop_column('projectinvitations', 'invited_id')
    op.create_table('otps',
    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('Asia/Bishkek'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('Asia/Bishkek'::text, now())"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('otps_pkey')),
    sa.UniqueConstraint('email', name=op.f('otps_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
